areas:
  - 札幌
  - 函館
  - 旭川
  - 室蘭
  - 苫小牧
  - 釧路
  - 知床
  - 帯広
  - 十勝
  - 北見
  - 青森
  - 弘前
  - 八戸
  - 盛岡
  - 岩手
  - 平泉
  - 仙台
  - 宮城
  - 秋田
  - 山形
  - 庄内
  - 福島
  - 会津
  - 郡山
  - 白河
  - いわき
  - 水戸
  - 土浦
  - つくば
  - 宇都宮
  - 日光
  - 那須
  - とちぎ
  - 前橋
  - 高崎
  - 群馬
  - 大宮
  - 川口
  - 川越
  - 所沢
  - 熊谷
  - 春日部
  - 越谷
  - 千葉
  - 成田
  - 市川
  - 船橋
  - 習志野
  - 袖ケ浦
  - 市原
  - 松戸
  - 野田
  - 柏
  - 品川
  - 世田谷
  - 練馬
  - 杉並
  - 板橋
  - 足立
  - 江東
  - 葛飾
  - 江戸川
  - 八王子
  - 多摩
  - 横浜
  - 川崎
  - 湘南
  - 相模
  - 山梨
  - 富士山
  - 新潟
  - 長岡
  - 上越
  - 富山
  - 金沢
  - 石川
  - 福井
  - 長野
  - 松本
  - 諏訪
  - 南信州
  - 安曇野
  - 岐阜
  - 飛騨
  - 静岡
  - 浜松
  - 沼津
  - 伊豆
  - 名古屋
  - 豊橋
  - 岡崎
  - 三河
  - 豊田
  - 一宮
  - 尾張小牧
  - 春日井
  - 三重
  - 四日市
  - 伊勢志摩
  - 鈴鹿
  - 滋賀
  - 京都
  - 大阪
  - なにわ
  - 堺
  - 和泉
  - 神戸
  - 姫路
  - 奈良
  - 飛鳥
  - 和歌山
  - 鳥取
  - 島根
  - 出雲
  - 岡山
  - 倉敷
  - 広島
  - 福山
  - 下関
  - 山口
  - 徳島
  - 高松
  - 香川
  - 愛媛
  - 高知
  - 福岡
  - 北九州
  - 久留米
  - 筑豊
  - 佐賀
  - 長崎
  - 佐世保
  - 熊本
  - 大分
  - 宮崎
  - 鹿児島
  - 奄美
  - 沖縄
hiragana:
  - あ
  - い
  - う
  - え
  - か
  - き
  - く
  - け
  - こ
  - さ
  - す
  - せ
  - そ
  - た
  - ち
  - つ
  - て
  - と
  - な
  - に
  - ぬ
  - ね
  - の
  - は
  - ひ
  - ふ
  - ほ
  - ま
  - み
  - む
  - め
  - も
  - や
  - ゆ
  - よ
  - ら
  - り
  - る
  - れ
  - ろ
  - わ
  - を
alphabet:
  - A
  - C
  - F
  - H
  - K
  - L
  - M
  - P
  - X
  - Y
numbers:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
symbols:
  - "-"
  - "·"
  - "・"
